ARG SPARK_TAG=3.2.0-hive2.3.9-java11-scala2.12-hadoop3.3.1
ARG JDK_VERISON=11
FROM maven:3.8-jdk-${JDK_VERISON} as maven

ARG DELTA_VERSION=1.1.0
COPY delta.xml delta.xml
RUN mvn --file=delta.xml dependency:copy-dependencies -Ddelta.version=${DELTA_VERSION} -DoutputDirectory=jars

FROM ghcr.io/khwj/data-platform-containers/spark:${SPARK_TAG}
COPY --from=maven jars/* /opt/spark/jars/