ARG JDK_VERSION
ARG SPARK_IMAGE_TAG
FROM maven:3.8-jdk-${JDK_VERSION} as maven

ARG DELTA_VERSION
COPY delta.xml delta.xml
RUN mvn --file=delta.xml dependency:copy-dependencies -Ddelta.version=${DELTA_VERSION} -DoutputDirectory=jars

FROM ghcr.io/khwj/data-platform-containers/spark:${SPARK_IMAGE_TAG}
COPY --from=maven jars/* /opt/spark/jars/