name: Build Polynote Container Image

on:
  workflow_dispatch:
    inputs:
      polynote_version:
        description: "Polynote version"
        required: true
        default: "0.4.4"
      scala_version:
        description: "Scala version"
        required: true
        default: "2.12"
      jdk_version:
        description: "JDK version"
        required: true
        default: "11"

jobs:
  publish_docker:
    name: "Build and publish container image for Hive standalone metastore ${{ github.event.inputs.hive_metastore_version }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./polynote
          build-args: |
            "POLYNOTE_VERSION=${{ github.event.inputs.polynote_version }}"
            "SCALA_VERSION=${{ github.event.inputs.scala_version }}"
            "JDK_VERSION=${{ github.event.inputs.jdk_version }}"
          tags: ghcr.io/${{ github.repository }}/polynote:${{ github.event.inputs.polynote_version }}-scala${{ github.event.inputs.scala_version }}-jdk${{ github.event.inputs.jdk_version }}
          push: true
