name: Spark with Hadoop

on:
  workflow_dispatch:
    inputs:
      spark_image_tag:
        description: "Spark base image tag"
        required: true
        default: "3.2.0-hive2.3.9-scala2.12-jdk11"
      hadoop_version:
        description: "Hadoop version"
        required: true
        default: "3.3.1"

jobs:
  publish_docker:
    name: "Build ghcr.io/khwj/data-platform-containers/spark:${{ github.event.inputs.spark_image_tag }}-hadoop${{ github.event.inputs.hadoop_version }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./spark
          file: ./spark/Dockerfile.hadoop
          build-args: |
            "SPARK_IMAGE_TAG=${{ github.event.inputs.spark_image_tag }}"
            "HADOOP_VERSION=${{ github.event.inputs.hadoop_version }}"
          tags: ghcr.io/khwj/data-platform-containers/spark:${{ github.event.inputs.spark_image_tag }}-hadoop${{ github.event.inputs.hadoop_version }}
          push: true
