name: Zeppelin with Spark

on:
  workflow_dispatch:
    inputs:
      spark_image_tag:
        description: "Spark base image tag"
        required: true
        default: "3.1.2-hive2.3.9-scala2.12-jdk8"
      zeppelin_version:
        description: "Zeppelin version"
        required: true
        default: "0.10.0"

jobs:
  publish_docker:
    name: "Build ghcr.io/khwj/data-platform-containers/zeppelin:${{ github.event.inputs.zeppelin_version }}-spark${{ github.event.inputs.spark_image_tag }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./zeppelin
          file: ./zeppelin/Dockerfile.spark
          build-args: |
            "SPARK_IMAGE_TAG=${{ github.event.inputs.spark_image_tag }}"
            "ZEPPELIN_VERSION=${{ github.event.inputs.zeppelin_version }}"
          tags: ghcr.io/khwj/data-platform-containers/zeppelin:${{ github.event.inputs.zeppelin_version }}-spark${{ github.event.inputs.spark_image_tag }}
          push: true
